<?php

$query              = [];
$query['return_to'] = isset($return_to) ? $return_to : '';
$query['remember']  = isset($remember) ? $remember : '';

$query = array_filter($query);

if ($query) {

    $query = '?' . http_build_query($query);

} else {

    $query = '';
}

if (!isset($user_id) || !isset($token)) {

    $formUrl = null;

} else {

    $formUrl = 'auth/mfa_device/' . $user_id . '/' . $token['salt'] . '/' . $token['token'] . $query;
    $formUrl = site_url($formUrl);
}

?>
<div class="container nails-module-auth mfa mfa-device mfa-device-ask">
    <div class="row text-center">
        <div class="col-sm-6 col-sm-offset-3">
            <div class="well well-lg">
                <?php

                echo form_open($formUrl);

                echo '<p>Please enter a code generated by your device below:</p>';

                $hasError = form_error('mfaCode') ? 'has-error' : '';
                echo '<div class="form-group ' . $hasError . '">';
                echo form_input('mfaCode', '', 'class="form-control text-center" placeholder="Enter Code Here"');
                echo form_error('mfaCode', '<p class="help-block">', '</p>');
                echo '</div>';

                echo '<button type="submit" class="btn btn-primary btn-block">Verify Code</button>';

                echo form_close()

                ?>
            </div>
        </div>
    </div>
</div>
