<?php

$aQuery = array_filter([
    'return_to' => $return_to,
    'remember'  => $remember,
]);

$sQuery   = !empty($aQuery) ? '?' . http_build_query($aQuery) : '';
$sFormUrl = null;

if (isset($user_id) && isset($token)) {
    $sFormUrl = 'auth/mfa/device/' . $user_id . '/' . $token['salt'] . '/' . $token['token'] . $sQuery;
    $sFormUrl = site_url($sFormUrl);
}

?>
<div class="nails-auth mfa mfa--device mfa--device--ask u-center-screen">
    <div class="panel">
        <h1 class="panel__header text-center">
            Two Factor Authentication
        </h1>
        <div class="panel__body">
            <p class="alert alert--danger <?=empty($error) ? 'hidden' : ''?>">
                <?=$error?>
            </p>
            <p class="alert alert--success <?=empty($success) ? 'hidden' : ''?>">
                <?=$success?>
            </p>
            <p class="alert alert--warning <?=empty($message) ? 'hidden' : ''?>">
                <?=$message?>
            </p>
            <p class="alert alert--info <?=empty($info) ? 'hidden' : ''?>">
                <?=$info?>
            </p>
            <?=form_open($sFormUrl)?>
            <?php
            $sFieldKey         = 'mfa_code';
            $sFieldLabel       = 'Please enter a code generated by your device:';
            $sFieldPlaceholder = 'Enter a code generated by your device';
            ?>
            <div class="form__group <?=form_error($sFieldKey) ? 'has-error' : ''?>">
                <label for="input-<?=$sFieldKey?>"><?=$sFieldLabel?></label>
                <?=form_text($sFieldKey, set_value($sFieldKey), 'id="input-' . $sFieldKey . '" autocomplete="off" placeholder="' . $sFieldPlaceholder . '"')?>
                <?=form_error($sFieldKey, '<p class="help-block">', '</p>')?>
            </div>
            <p>
                <button type="submit" class="btn btn--block btn--primary">
                    Verify code &amp; Sign in
                </button>
            </p>
            <?=form_close()?>
        </div>
    </div>
</div>
