<?php

$aQuery = array_filter([
    'return_to' => $return_to,
    'remember'  => $remember,
]);

$sQuery = !empty($aQuery) ? '?' . http_build_query($aQuery) : '';

?>
<div class="nails-auth mfa mfa--device mfa--device--setup u-center-screen">
    <div class="panel">
        <h1 class="panel__header text-center">
            Set up Two Factor Authentication
        </h1>
        <div class="panel__body">
            <p class="alert alert--danger <?=empty($error) ? 'hidden' : ''?>">
                <?=$error?>
            </p>
            <p class="alert alert--success <?=empty($success) ? 'hidden' : ''?>">
                <?=$success?>
            </p>
            <p class="alert alert--warning <?=empty($message) ? 'hidden' : ''?>">
                <?=$message?>
            </p>
            <p class="alert alert--info <?=empty($info) ? 'hidden' : ''?>">
                <?=$info?>
            </p>
            <?=form_open('auth/mfa/device/' . $user_id . '/' . $token['salt'] . '/' . $token['token'] . $sQuery)?>
            <?=form_hidden('mfa_secret', $secret['secret'])?>
            <p>
                This site requires that you use Two Factor Authentication when logging in. To set up, please scan the QR
                code with your device, then enter a valid code.
            </p>
            <p class="text-center">
                <?=img(['src' => $secret['url'], 'class' => 'img-responsive img-thumbnail'])?>
            </p>
            <?php
            $sFieldKey         = 'mfa_code';
            $sFieldLabel       = 'Your code';
            $sFieldPlaceholder = 'Enter a code generated by your device';
            ?>
            <div class="form__group <?=form_error($sFieldKey) ? 'has-error' : ''?>">
                <label for="input-<?=$sFieldKey?>"><?=$sFieldLabel?></label>
                <?=form_text($sFieldKey, set_value($sFieldKey), 'id="input-' . $sFieldKey . '" autocomplete="off" placeholder="' . $sFieldPlaceholder . '"')?>
                <?=form_error($sFieldKey, '<p class="form__error">', '</p>')?>
            </div>
            <p>
                <button type="submit" class="btn btn--block btn--primary">
                    Verify code &amp; Sign in
                </button>
            </p>
            <?=form_close()?>
        </div>
    </div>
</div>
